service: hakuhagu
app: hakuhagu
org: hakuhagu

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1

functions:
  welcome:
    handler: handler.welcome
    events:
      - http:
          path: welcome
          method: post
  userRegistration:
    handler: handler.userRegistration
    events:
      - http:
          path: user/registration
          method: post
  itemRegistration:
    handler: handler.itemRegistration
    events:
      - http:
          path: item/registration
          method: post
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: post
