service: hakuhagu
app: hakuhagu
org: hakuhagu

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1

functions:
  welcome:
    handler: handler.welcome
    events:
      - http:
          path: welcome
          method: post
  userRegistration:
    handler: handler.userRegistration
    events:
      - http:
          path: user/registration
          method: post
  userAuthentication:
    handler: handler.userAuthentication
    events:
      - http:
          path: user/authentication
          method: get
  userInformation:
    handler: handler.userInformation
    events:
      - http:
          path: user/information
          method: post
  itemRegistration:
    handler: handler.itemRegistration
    events:
      - http:
          path: item/registration
          method: post
  imageUploadTest:
    handler: handler.imageUploadTest
    events:
      - http:
          path: image
          method: post
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: post
